//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoicing()
        {
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }
    
        public int IdInvoicing { get; set; }
        public Nullable<int> IdFlat { get; set; }
        public Nullable<int> IdServicesRegion { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdMonth { get; set; }
        public Nullable<int> IdYear { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Month Month { get; set; }
        public virtual ServicesRegion ServicesRegion { get; set; }
        public virtual Status Status { get; set; }
        public virtual Year Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}
