//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int IdPaymentHistory { get; set; }
        public int IdFlat { get; set; }
        public int IdServicesRegion { get; set; }
        public int IdInvoicing { get; set; }
        public Nullable<int> IdMonth { get; set; }
        public Nullable<int> IdYear { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Invoicing Invoicing { get; set; }
        public virtual Month Month { get; set; }
        public virtual ServicesRegion ServicesRegion { get; set; }
        public virtual Year Year { get; set; }
    }
}
