//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicesRegion()
        {
            this.Invoicing = new HashSet<Invoicing>();
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }
    
        public int IdServicesRegion { get; set; }
        public int IdServices { get; set; }
        public int IdRegions { get; set; }
        public Nullable<int> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoicing> Invoicing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Services Services { get; set; }
    }
}
