//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IdFlat { get; set; }
        public Nullable<int> IdRole { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Role Role { get; set; }
    }
}
